version: '3.8'

services:
  cuda-service:
    env_file:
      .env
    build: .
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${STORAGE_PATH}:/storage
    ports:
      - "8000:8000"