version: '3.8'

services:
  cuda-service:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./storage:/storage
    ports:
      - "8000:8000"
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            count: 1
            capabilities: [gpu]
