FROM ubuntu:20.04

# Set the working directory in the container
WORKDIR /app

RUN apt-get update && apt-get install -y \
    nvidia-docker2 \
    libnvcuvid1 \
    ffmpeg \
    python3 \
    python3-pip \
    && rm -rf /var/lib/apt/lists/*
